version: '3.8'
services:
  app: 
    build:
      context: ../
      dockerfile: Dockerfile
    command: python main.py
    environment:
      ENGINE: pandas
      APP_HOST: 0.0.0.0
      APP_PORT: 8888
    ports: 
      - "8888:8888"
    volumes:
      - "../data:/home/user/app/data"
#volumes:
#  local_pgdata: